apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: my_db
spec:
  containers:
  - name: my-db
    image: 579130819361.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"