apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: 579130819361.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: 10-244-0-5.db.pod.cluster.local #10-244-0-5.db.pod.cluster.local or mysql-service.db.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"