apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  containers:
  - name: employees
    image: 579130819361.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: 10-244-0-5.db.pod.cluster.local
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"